enum AuthCategory {
  financial,
  communication,
  socialMedia,
  work,
  entertainment,
  business,
  government,
  health,
  tech,
  others,
}

Map<AuthCategory, String> authCategoryStrings = {
  AuthCategory.financial: "Financial",
  AuthCategory.communication: "Communication",
  AuthCategory.socialMedia: "Social Media",
  AuthCategory.work: "Work",
  AuthCategory.entertainment: "Entertainment",
  AuthCategory.business: "Business",
  AuthCategory.government: "Government",
  AuthCategory.health: "Health",
  AuthCategory.tech: "Tech",
  AuthCategory.others: "Others",
};

Map<AuthCategory, List<String>> authCategoryTags = {
  AuthCategory.financial: [
    "Bank Account",
    "Credit Card",
    "Insurance",
    "Investments",
    "Tax Filing",
    "Loans",
  ],
  AuthCategory.communication: [
    "Email",
    "Phone Number",
    "Messaging Apps",
    "VoIP Services",
    "Contact Management",
  ],
  AuthCategory.socialMedia: [
    "Facebook",
    "Instagram",
    "Twitter",
    "LinkedIn",
    "Snapchat",
    "TikTok",
  ],
  AuthCategory.work: [
    "Project Management",
    "Time Tracking",
    "Workplace Chat",
    "Freelancing Platforms",
    "Remote Work Tools",
  ],
  AuthCategory.entertainment: [
    "Streaming Services",
    "Gaming Accounts",
    "Music Platforms",
    "E-books",
    "Movie Tickets",
  ],
  AuthCategory.business: [
    "CRM Tools",
    "ERP Systems",
    "Business Email",
    "Cloud Storage",
    "Accounting Software",
  ],
  AuthCategory.government: [
    "National ID",
    "Passport",
    "Driver's License",
    "Social Security",
    "Voter Registration",
  ],
  AuthCategory.health: [
    "Health Insurance",
    "Fitness Apps",
    "Doctor Portals",
    "Vaccination Records",
    "Lab Reports",
  ],
  AuthCategory.tech: [
    "Developer Accounts",
    "GitHub",
    "API Keys",
    "Cloud Platforms",
    "Software Subscriptions",
  ],
  AuthCategory.others: [
    "Miscellaneous",
    "Uncategorized",
    "Custom Entries",
  ],
};
