// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVFInB70GRfc41q8e3SdxF9d7ohXRhbTM',
    appId: '1:340957486786:web:94918080297faa4d37e55b',
    messagingSenderId: '340957486786',
    projectId: 'reauth-cf863',
    authDomain: 'reauth-cf863.firebaseapp.com',
    storageBucket: 'reauth-cf863.appspot.com',
    measurementId: 'G-DQE7E8PS54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9w35lktZ3-aLtjxwA35fkI55o7Mvg4g',
    appId: '1:340957486786:android:ac76be9ac251f92c37e55b',
    messagingSenderId: '340957486786',
    projectId: 'reauth-cf863',
    storageBucket: 'reauth-cf863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjEhJlI_tt_FM6WRH4fbzKx5vdqmayPOE',
    appId: '1:340957486786:ios:61b0c841afbc6a7437e55b',
    messagingSenderId: '340957486786',
    projectId: 'reauth-cf863',
    storageBucket: 'reauth-cf863.appspot.com',
    androidClientId: '340957486786-8sl68jf2c4m7l2cti1pe7vumdcbs7liu.apps.googleusercontent.com',
    iosBundleId: 'com.example.reauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjEhJlI_tt_FM6WRH4fbzKx5vdqmayPOE',
    appId: '1:340957486786:ios:61b0c841afbc6a7437e55b',
    messagingSenderId: '340957486786',
    projectId: 'reauth-cf863',
    storageBucket: 'reauth-cf863.appspot.com',
    androidClientId: '340957486786-8sl68jf2c4m7l2cti1pe7vumdcbs7liu.apps.googleusercontent.com',
    iosBundleId: 'com.example.reauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVFInB70GRfc41q8e3SdxF9d7ohXRhbTM',
    appId: '1:340957486786:web:8732afef28cdbc1837e55b',
    messagingSenderId: '340957486786',
    projectId: 'reauth-cf863',
    authDomain: 'reauth-cf863.firebaseapp.com',
    storageBucket: 'reauth-cf863.appspot.com',
    measurementId: 'G-6FTZQ68QVV',
  );
}
